add base.
Kaminari26/java-shareit pull request #1
Opened 2023-05-26 12:49 UTC by Kaminari26

В группе сказали что сам шеринг можно не делать, так как этого прямо не требует тз и не тестирует. это странно, но я сделал как сказали

2023-05-27 16:08 UTC, YazykovMikhail requested changes

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String status;
В этой работе это не нуэено, да. 
Сущность можешь оставить, но логику лучше не использовать

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * TODO Sprint add-controllers.
Эти комментарии стоит убирать, когла ты реализовал код. 
Они елаются как раз что бы не забыть что то сделать.
Везде где реализовал, убери их

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Booking request;
В этой работе убери от сюда

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
под маппер лучше сделать отлену папку

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    IUserService userService;
модификатор доступа и final

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemStorage.searchItem(query);
стоит сделать проверку
if (text == null || text.isBlank()) {
			return Collections.emptyList();
		}

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        return userStorage.updateUser(userDto, userId);
Стораджи уже работают с моделью. 
Т.е весь мапинг из dto->model должен быть в сервисе. 
А в  сторадж передается уже готовая модель

Поправь это везде

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    public UserDto update(UserDto userDto, Long userId) {
Вот например пример метода:

```
@Override
	public ItemDto updateItem(long userId, ItemDto itemDto) {
		Item item = itemRepository.findById(itemDto.getId());
		if (item == null || item.getOwner().getId() != userId) {
			throw new NotFoundException("Item with id=" + itemDto.getId() + " not found");
		}
		if (itemDto.getName() != null) {
			item.setName(itemDto.getName());
		}
		if (itemDto.getDescription() != null) {
			item.setDescription(itemDto.getDescription());
		}
		if (itemDto.getAvailable() != null) {
			item.setAvailable(itemDto.getAvailable());
		}

		itemRepository.update(item);
		return ItemMapper.toItemDto(item);
	}
	
```
обрати внмиание, все проверки и безнес логика находится в сервисе. 
Сторадж - это слой работы с базорй данных, а не с бизнес логикой. Для логике есть слой сервиса. Поправь это для всех методов

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +        if (text.isBlank()) {
все проверки делаются в сервисе. 
Так же обрати внимание, если текст null ,то будет, null.isBlank() -> NPE

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    IUserService iUserService;
Сорадж не может обращаться к сервису. 
Это логика проверок должна быть на уровне сервиса

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
модификатор доступа, final

2023-05-27 16:08 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@Slf4j
Нигде нет в логах какой обьект вернулся на запрос. 
Потом будет не разобарться, отработал метод или нет. 
Поправь везде

2023-05-28 09:18 UTC, YazykovMikhail commented
Не забывай отмечать поправленные комментарии

2023-05-28 09:28 UTC, YazykovMikhail approved these changes

2023-05-28 09:28 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserStorage.java
> +    HashMap<Long, User> users = new HashMap<>();
Если есть замечание в одном месте, посмотри и дургие аналогичные

2023-05-28 09:28 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserStorage.java
> +    public HashMap<Long, User> getUsers() {
Такой метод не нужен. 
Ты возвращешь реализацию хранилища, завтра будет БД, ты же не сможешь вернуть БД.

2023-05-28 09:28 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    public HashMap<Long, Item> getAllItemsDefault() {
Такой метод не нужен. 
Ты возвращешь реализацию хранилища, завтра будет БД, ты же не сможешь вернуть БД.

2023-05-28 09:28 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    @SneakyThrows
лучше это убрать и сделать исключение от RunTime

2023-05-28 09:28 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            throw new UserNotFoundException("Пользователь не найден");
Наслдуй исключение от RunTimeException

2023-05-28 13:58 UTC, Kaminari26 commented on src/main/java/ru/practicum/shareit/user/UserStorage.java
> +    public HashMap<Long, User> getUsers() {
Так мне нужен лист дто, как мне тогда его вернуть, если превращаю в одном месте а хранится в другом?

2023-06-02 23:47 UTC, merged