Я не доделал, заливаю что бы показать что жив. Работа + учеба убивает…
Kaminari26/java-shareit pull request #2
Opened 2023-06-12 14:20 UTC by Kaminari26

… конечно

2023-06-13 14:24 UTC, YazykovMikhail commented
Название коммитов должно быть содержательным, и передавать смысл того что там сделано. 

Коммиты такого содержания: 
@Kaminari26
[Я не доделал, заливаю что бы показать что жив. Работа + учеба убивает…](https://github.com/Kaminari26/java-shareit/pull/2/commits/29b5f646fa3f4317429ad949aabfbaa07e635be5) 
29b5f64
… конечно
@Kaminari26
Я не доделал, заливаю что бы показать что жив. Работа + учеба убивает… 
8cc87a8
… конечно
@Kaminari26


[Я не доделал, заливаю что бы показать что жив. Работа + учеба убивает…](https://github.com/Kaminari26/java-shareit/pull/2/commits/8cc87a8bdb5945cba991396c43f6549bde571b95) 
[de1e5f7](https://github.com/Kaminari26/java-shareit/pull/2/commits/de1e5f786095cf2290a8692bbb70c44bcdc46f87)

Это не очень, ты делаешь комиты не для проверяющих, а для себя и твоих товарищей

2023-06-13 14:36 UTC, YazykovMikhail requested changes

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/dto/IBookingService.java
> +package ru.practicum.shareit.booking.dto;
этот класс точно долден быть не в этом пакете

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/dto/State.java
> +package ru.practicum.shareit.booking.dto;
этот класс точно долден быть не в этом пакете

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +package ru.practicum.shareit.booking.dto;
Этот класс тоже лучше не в этт пакет. 

Можно сделать папки
service
repository
 и так далее

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDtoResponse createBooking(@Valid @RequestBody BookingDto bookingDto, @RequestHeader("X-Sharer-User-Id") Long owner) {
У тебя в dto есть поле id, разве оно приходит в запросе?
dto для этого и нужны, что бы там были толкьо те поля, которые нужны.

CreateBookingRequestDto - можно вот так если нужно специфичное dto. 
И так можно для каждого контроллера по необходимости

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +  request_id BIGINT,
пока это реализовывать не нужно. 
Ведь если ты сейчас это реализушь, а код нет. То потом в коде не будет изменения бд и картинка будет не полная. А в каждом ПР должны быть только те изменения, которые отвечают за текущее задание

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests (
пока это реализовывать не нужно.
Ведь если ты сейчас это реализушь, а код нет. То потом в коде не будет изменения бд и картинка будет не полная. А в каждом ПР должны быть только те изменения, которые отвечают за текущее задание

2023-06-13 14:36 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS items (
Копипаст? Помоему это лишнее

2023-06-14 14:55 UTC, YazykovMikhail requested changes

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Long itemId;
@ManyToOne
	@JoinColumn(name = "item_id")
	private Item item;

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Long booker;
@ManyToOne
	@JoinColumn(name = "booker_id")
	private User booker;

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> -    private User booker;
Было верно, нуюно было только таблицы связать связью

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long owner;
@ManyToOne(optional = false)
	@JoinColumn(name = "owner_id", nullable = false)
	private User owner;

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +    @ManyToOne
А тут верно, молодец

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findByBookerAndStartIsAfterAndStatusIs(userId, dateNow, sort, BookingStatusEnum.REJECTED);
bookings = bookingRepository.findCanceled(userId, sort);


лучше так:
```
@Query(" select b " +
			"from Booking b " +
			"where b.booker.id = ?1 " +
			"  and (b.status = 'CANCELED' or b.status = 'REJECTED' )")
	List<Booking> findCanceled(Long bookerId, Sort sort);
```

2023-06-14 14:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findByItemIdInAndStartIsAfterAndStatusIs(itemIdList, dateNow, sort, BookingStatusEnum.REJECTED);
@Query(" select b " +
			"from Booking b " +
			"where b.item.owner.id = ?1 " +
			"  and (b.status = 'CANCELED' or b.status = 'REJECTED' )")
	List<Booking> findOwnerCanceled(Long bookerId, Sort sort);

2023-06-15 20:42 UTC, Kaminari26 commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +    @ManyToOne
угадал

2023-06-16 12:34 UTC, YazykovMikhail approved these changes

2023-06-16 12:34 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +  request_id BIGINT,
ты поправил этот комментарийЕ отмесай его решенным. Как и все, что ты поправил

2023-06-16 14:19 UTC, merged